### PR TITLE
Add possibility to set seed when boostrapping

### PR DESCRIPTION
**Pull request by dramanica**

### CODE REVIEW

**Comment by dramanica** [comment]
@ejolly Actually, hold this, it looks like something is wrong with the unit tests. Let me check why they fail on GitHubActions

**Comment by dramanica** [comment]
@ejolly In case you didn't see, the tests were fixed.

**Comment by ejolly** [comment]
Awesome thanks! Will merge by the end of the week.

**Comment by dramanica** [comment]
@ejolly Would some plotting routines for diagnosing lmer and glmer be of interest? I could make a separate pull request with those for you to have a look if you think they might be helpful.

**Comment by ejolly** [comment]
Absolutely! That would actually be fantastic! Feel free to use the existing
plotting methods on model classes as a starting point, or even rewriting
them completely. My hope was to eventually have a consistent plotting API
for all model types, with extra args and kwargs for Lmer models, similar to
how .fit() works.

**Comment by dramanica** [comment]
@ejolly Fair enough. Just revert the cooks distance stuff (or do you want me to do it?), and I'll create another PR with that functionality and the plots when I have a second. 
Not sure how I managed to copy over the Lmer.py file in that directory, sorry about that!

**Comment by ejolly** [comment]
Sure thing I can revert those commits and merge this if you want to take a shot at a new PR

**Pull request merged**
